#!/usr/bin/env python3
"""Generate a 5-point star OBJ mesh. Run: python3 generate_star.py"""
import math

R = 0.5      # outer radius
r = 0.2      # inner radius
thick = 0.08 # thickness in Z

# 10 perimeter vertices in order around the star
verts = []
for k in range(5):
    angle = math.radians(90 - k * 72)
    verts.append((R * math.cos(angle), R * math.sin(angle)))
    angle_inner = math.radians(90 - k * 72 - 36)
    verts.append((r * math.cos(angle_inner), r * math.sin(angle_inner)))

lines = ["# 5-point star generated by generate_star.py"]
# Front face vertices (z = +thick/2)
zf = thick / 2.0
lines.append(f"v 0 0 {zf:.6f}")  # 1: center front
for x, y in verts:
    lines.append(f"v {x:.6f} {y:.6f} {zf:.6f}")
# Back face vertices (z = -thick/2)
zb = -thick / 2.0
lines.append(f"v 0 0 {zb:.6f}")  # 12: center back
for x, y in verts:
    lines.append(f"v {x:.6f} {y:.6f} {zb:.6f}")

# Indices (1-based)
# Front: 1 (center front), 2..11 (perimeter front)
# Back:  12 (center back),  13..22 (perimeter back)

# Front triangles (fan from center)
for i in range(10):
    nxt = 2 + (i + 1) % 10
    lines.append(f"f 1 {2 + i} {nxt}")

# Back triangles (fan from center, reversed winding for outward normal)
for i in range(10):
    nxt = 13 + (i + 1) % 10
    lines.append(f"f 12 {nxt} {13 + i}")

# Side triangles (quads split along shorter diagonal)
for i in range(10):
    nxt = 2 + (i + 1) % 10
    fi = 2 + i       # front vertex i
    fn = nxt         # front vertex i+1
    bi = 13 + i      # back vertex i
    bn = 13 + (i + 1) % 10  # back vertex i+1
    # Two triangles per quad: (fi, fn, bi) and (fn, bn, bi)
    lines.append(f"f {fi} {fn} {bi}")
    lines.append(f"f {fn} {bn} {bi}")

print("\n".join(lines))